#!/usr/bin/env bash

version="v0.99"
scriptDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

colorOff="\033[0m"    ;  NC="${colorOff}"
grey="\033[1;30m"     ;  l1="${grey}.${NC}"
blue="\033[0;34m"     ;  l2="${grey}..${NC}"
green="\033[0;32m"    ;  l3="${grey}...${NC}"
red="\033[0;31m"      ;  l4="${grey}....${NC}"
purple="\033[0;35m"   ;  l5="${grey}.....${NC}"
orange="\033[0;33m"   ;  l6="${grey}......${NC}"
cyan="\033[0;36m"     ;  l7="${grey}.......${NC}"
bBlue="\033[1;34m"    ;  l8="${grey}........${NC}"
bGreen="\033[1;32m"   ;  uCyan="\033[4;36m"
bRed="\033[1;31m"     ;
bPurple="\033[1;35m"  ;
bOrange="\033[1;33m"  ;
uBlue="\033[4;34m"    ;
uGreen="\033[4;32m"   ;
uRed="\033[4;31m"     ;
uPurple="\033[4;35m"  ;
uOrange="\033[4;33m"  ;

i=1
for arg in "$@"; do
    case "${arg}" in
        '-v' | '--version')
            showVersion=true
            ;;
        '-U' | '--update')
            update=true
            ;;
        '-h' | '--help')
            showHelp=true
            ;;
        '-l' | '--local')
            nextArg=$((i+1))
            localDIR=${!nextArg}
            ;;
        "-r" | '--remote')
            nextArg=$((i+1))
            remoteDIR=${!nextArg}
            ;;
        '-u' | '--user')
            nextArg=$((i+1))
            user=${!nextArg}
            ;;
        '-m' | '--machine')
            nextArg=$((i+1))
            machine=${!nextArg}
            ;;
        '-i' | '-ip' | '--ip' | '--addr' | '--addrs' | '--address' | '--ip-address' | '--ip-addr' | '--ip-addrs')
            nextArg=$((i+1))
            ip=${!nextArg}
            ;;
        *)
    echo "$arg"
            ;;
    esac
    ((i++))
done

if [[ -z "$machine" ]]; then
    machine="$1"
fi

if [[ $update ]];then
    printf "feature not done yet\n"
elif [[ $showVersion ]]; then
    printf "mountSSH verison: ${orange}${version}${NC}\n"
elif [[ $showHelp || "$1" == "" ]]; then
    printf "syntax:\n"
    printf "${l2}${uOrange}help${colorOff}\n"
    printf "${l4}selector: '${orange}-h${NC}', '${orange}--help${NC}'\n"
    printf "${l2}${uBlue}machine${colorOff}\n"
    printf "${l4}selector: '${blue}-m${NC}', '${blue}--machine${NC}'\n"
    printf "${l2}${uGreen}user${colorOff}\n"
    printf "${l4}selector: '${green}-u${NC}', '${green}--user${NC}'\n"
    printf "${l2}${uRed}localDIR${colorOff}\n"
    printf "${l4}selector: '${red}-l${NC}', '${red}--local${NC}'\n"
    printf "${l2}${uPurple}remoteDIR${colorOff}\n"
    printf "${l4}selector: '${purple}-r${NC}', '${purple}--remote${NC}'\n"
    printf "${l2}${uCyan}ip address${colorOff}\n"
    printf "${l4}selector: '${cyan}-i${NC}', '${cyan}--ip${NC}'\n"
else
    machineName=$(jq ".[\"${machine}\"].machine_name" ${scriptDIR}/machines.json)
    if [[ ${machineName} == null ]]; then
        machineName="${machine}"
    else
        machineName=$(jq -r ".[\"${machine}\"].machine_name" ${scriptDIR}/machines.json)
    fi


    printf "${cyan}attempting to mount: ${NC}${orange}${machine}${NC}\n"
    
    if [[ $(jq -r "._tailscale" ${scriptDIR}/machines.json) == true && -z "$ip" ]]; then
        printf "${l2}${bPurple}tailscale enabled${NC}\n"
        machineTailscale=$(jq -r ".[\"${machine}\"].tailscale" ${scriptDIR}/machines.json)
        if [[ ${machineTailscale} == true || "${machineTailscale}" == "null" ]]; then
            #detect IP from tailscale
            ip="$(tailscale ip ${machine} | sed -n '1p')"
            printf "${l4}${bPurple}detected ip:\n${grey}....${NC}${orange}${ip}${NC}\n"
        else
            printf "${l3}${bPurple}however it's disabled for this machine${NC}\n"
            ip="${machine}"
            printf "${l4}${bPurple}using ip:\n${grey}....${NC}${orange}${ip}${NC}\n"
        fi
    elif [[ -z "$ip" ]]; then
        ip="${machine}"
        printf "${l4}${bPurple}using ip:\n${grey}....${NC}${orange}${ip}${NC}\n"
    else
        printf "${l4}${bPurple}using ip:\n${grey}....${NC}${orange}${ip}${NC}\n"
    fi

    printf "${l2}${bPurple}checking user${NC}\n"
    #if no input for the user,
    #  then default to ${USER}
    if [[ "$user" == "" ]]; then
        configuredUser=$(jq -r ".[\"${machine}\"].user" ${scriptDIR}/machines.json)
        if [[ "${configuredUser}" != null ]]; then
            printf "${l4}${green}using preconfigured user${NC}\n"
            user="${configuredUser}"
        else
            printf "${l4}${green}defaulting to local user${NC}\n"
            user="${USER}"
        fi
    fi
    printf "${l4}${orange}${user}${NC}\n"
    
    printf "${l2}${bPurple}checking local dir${NC}\n"
    if [[ -z "${localDIR}" ]]; then
        #if the user didn't input dir, then check for pre-configured dir
        configuredLocDir=$(jq -r ".[\"${machine}\"].local_dir" ${scriptDIR}/machines.json)
        if [[ "${configuredLocDir}" != "null" ]]; then
            printf "${l4}${green}using preconfigured local dir${NC}\n"
            localDIR="${configuredLocDir}"
        else #if not preconfigured, then use current dir
            printf "${l4}${green}defaulting to current local directory${NC}\n"
            localDIR="${PWD}/${machineName}"
        fi
    fi
    printf "${l4}${orange}${localDIR}${NC}\n"

    printf "${l2}${bPurple}checking remote dir${NC}\n"
    if [[ -z "${remoteDIR}" ]]; then
        #if the user didn't input dir, then check for pre-configured dir
        configuredRemDir=$(jq -r ".[\"${machine}\"].remote_dir" ${scriptDIR}/machines.json)
        if [[ "${configuredRemDir}" != "null" ]]; then
            printf "${l4}${green}using configured remote dir${NC}\n"
            remoteDIR="${configuredRemDir}"
        else #if not preconfigured, then use current dir
            printf "${l4}${green}default remote dir${NC}\n"
            remoteDIR="/home/${user}"
        fi
    else
        remoteDIR="${remoteDIR}"
    fi
    printf "${l4}${orange}${remoteDIR}${NC}\n"

    #if the local dir does not exist, then create it
    if [[ $(ls "${localDIR}" &> /dev/null;printf "$?") == 2 ]]; then
        printf "${l2}${bRed}local dir does not exist${NC}\n${l4}${bGreen}creating local dir${NC}\n"
        mkdir "${localDIR}"
    fi

    printf "${l2}${cyan}mounting...${NC}\n"
    #attempt to mount
    sshfs ${user}@${ip}:"${remoteDIR}" "${localDIR}"
fi
